---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  labels:
    app: schema-registry-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30881
  selector:
    app: schema-registry
