---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
  - kafka.yml
  - topics.yml

bases:
  - ../katalog/kafka-operator
  - ../katalog/kafka-monitoring
  - ../katalog/kafka-manager
  - ../katalog/kafka-addons/kafka-rebalance

patchesStrategicMerge:
  - patches/kafka-rebalance.yml
  - patches/kafka-monitoring-connect.yml

secretGenerator:
  - name: kafka-manager-credential
    envs:
      - secret/kafka-manager-credential.env

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kafka-manager
    path: patches/kafka-manager.yml
  - target:
      group: kafka.strimzi.io
      version: v1beta1
      kind: Kafka
      name: cluster-example
    path: patches/kafka-kind.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: strimzi-cluster-operator
    path: patches/strimzi-operator.yml
