---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-operator

resources:
  - namespace.yaml
  - cluster-operator.yaml

images:
  - name: quay.io/strimzi/operator
    newName: registry.sighup.io/fury/strimzi/operator

patchesStrategicMerge:
  - patch-images.yaml
