---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - kafka-manager
              topologyKey: kubernetes.io/hostname
      containers:
        - name: kafka-manager
          image: kafkamanager/kafka-manager:3.0.0.4
          env:
            - name: ZK_HOSTS
              value: zookeeper-nodes:2181
            - name: KAFKA_MANAGER_AUTH_ENABLED
              value: "true"
            - name: KAFKA_MANAGER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-manager-credential
                  key: username
            - name: KAFKA_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-manager-credential
                  key: password
