# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: example-topic-1
  labels:
    strimzi.io/cluster: sighup-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000 # 2hr retention
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: example-topic-2
  labels:
    strimzi.io/cluster: sighup-kafka-cluster
spec:
  partitions: 25
  replicas: 3
  config:
    retention.ms: 7200000 # 2hr retention